### ISSUE TITLE
CNN models

### ISSUE THREAD

**Issue by wzhCUMT** [HearingTechnology/CoNNear_IHC-ANF#1]
Dear Mr./Ms. Fotios Drakopoulos and Relevant researchers ,

@fotisdr @HearingTechnology Thank you very much for shared the excellent code!
Could you please share the CNN code of CoNNear(cochlea), CoNNear(IHC–ANF), and CoNNear(IHC–ANF).
Sincerely thank you for your help！

Best Wishes,
wzh

**Comment by fotisdr** [comment]
Dear wzh,

What do you mean by the CNN code? The CNN model of CoNNear<sub>cochlea</sub> can be found in the *connear* folder of the [CoNNear_cochlea ](https://github.com/HearingTechnology/CoNNear_cochlea) repository, while the CNN models of the CoNNear<sub>IHC</sub> and CoNNear<sub>ANF</sub> can be found in the *connear* folder of this repository (json and h5 files that can be loaded in Tensorflow/Keras). Example scripts can also be found in both repositories on how to run the models.

Best,
Fotios

**Comment by wzhCUMT** [comment]
> 亲爱的wz，
> 
> CNN 代码是什么意思？CoNNear cochlea的 CNN 模型可以在 CoNNear_cochlea 存储库的[connear](https://github.com/HearingTechnology/CoNNear_cochlea)_文件_夹中找到，而 CoNNear IHC和 CoNNear ANF的 CNN 模型可以在此存储库的_connear_文件夹中找到（可以在 Tensorflow 中加载的 json 和 h5 文件） /凯拉斯）。还可以在两个存储库中找到有关如何运行模型的示例脚本。[](https://github.com/HearingTechnology/CoNNear_cochlea)__
> 
> 最好的， Fotios

**Comment by wzhCUMT** [comment]
> > 亲爱的wz，
> > CNN 代码是什么意思？CoNNear cochlea的 CNN 模型可以在 CoNNear_cochlea 存储库的[connear](https://github.com/HearingTechnology/CoNNear_cochlea)_文件_夹中找到，而 CoNNear IHC和 CoNNear ANF的 CNN 模型可以在此存储库的_connear_文件夹中找到（可以在 Tensorflow 中加载的 json 和 h5 文件） /凯拉斯）。还可以在两个存储库中找到有关如何运行模型的示例脚本。__
> > 最好的， Fotios

**Comment by wzhCUMT** [comment]
Dear Mr. Fotios,

Thanks a lot for your quick reply!
I want to learn how you use _tensorflow_ to build the CNN code of CoNNear_cochlea, CoNNearIHC, and CoNNearANF.
However, I can only see the structure and parameters of the CNN model by loading the josn and h5 files in the _connear_ folder.
So, could you please share it.

Cheers,
wzh

**Comment by fotisdr** [comment]
Dear wzh,

I see, sorry for the misunderstanding. Unfortunately the Python scripts that were used to build and train each CoNNear model are not available at the moment, but the exact implementations of the CoNNear models are described in the published [CoNNear_cochlea](https://www.nature.com/articles/s42256-020-00286-8) and [CoNNear_IHC-ANF](https://www.nature.com/articles/s42003-021-02341-5) papers. You can contact me if you need additional help with that. Additionally, we plan on making public a repository that contains the whole CoNNear periphery model (cochlea+IHC+ANF) on the HearingTechnology profile the following days, perhaps this might be of help for you.

Cheers,
Fotios

EDIT: By the way, you can find the aforementioned repository here:
https://github.com/HearingTechnology/CoNNear_periphery

**Comment by wzhCUMT** [comment]
Very nice! Thank you very much for your help!
